#!/usr/bin/ruby
require 'libRubyROOT'
require 'getoptlong'
opts=GetoptLong.new(
	["--logo","-l",GetoptLong::REQUIRED_ARGUMENT],
	["--help","-h",GetoptLong::NO_ARGUMENT],
	["--output-file","-o",GetoptLong::REQUIRED_ARGUMENT]
)
opts_hash={}
opts.each{ |opt, arg|
	opts_hash[opt]=arg
}
puts "Usage:
	plotsum [-l logo] -o output-file file1 file2 ...
" if opts_hash["--help"]==""
exit if ARGV==[]
opts_hash["--logo"]="" if opts_hash["--logo"]==nil
f=TFile.new(ARGV[0],"r")
i=TIter.new(f.GetListOfKeys)
hist_probe=f.Get(i.Next.GetName).as("TH1F")
nbins=hist_probe.GetNbinsX.to_f
xmin=hist_probe.GetXaxis.GetXmin.to_f
xmax=hist_probe.GetXaxis.GetXmax.to_f
f.Close
p opts_hash["--logo"]
output=TFile.new(opts_hash["--output-file"],"new")
sum=TH1F.new(opts_hash["--logo"],opts_hash["--logo"],nbins,xmin,xmax)
ARGV.each {|file|
	f=TFile.new(file,"r")
	i=TIter.new(f.GetListOfKeys)
	hist=f.Get(i.Next.GetName).as("TH1F")
	sum.Add(sum,hist,1,1)
        f.Close
}
output.Write
output.Close
