#!/usr/bin/ruby
require 'libRubyROOT'
require 'getoptlong'
opts=GetoptLong.new(
	["--logo","-l",GetoptLong::REQUIRED_ARGUMENT],
	["--help","-h",GetoptLong::NO_ARGUMENT],
	["--output-file","-o",GetoptLong::REQUIRED_ARGUMENT]
)
opts_hash={}
opts.each{ |opt, arg|
	opts_hash[opt]=arg
}
puts "Usage:
	plotdelta [-l logo] -o output-file file1 file2 ...
  result (dist1-dist2)/dist2
" if opts_hash["--help"]==""
exit if ARGV.size!=2
opts_hash["--logo"]="" if opts_hash["--logo"]==nil

f1=TFile.new(ARGV[0],"r")
i=TIter.new(f1.GetListOfKeys)
positive=f1.Get(i.Next.GetName).as("TH1F")
total=positive.Clone
total.SetDirectory(0)
f1.Close
f2=TFile.new(ARGV[1],"r")
i=TIter.new(f2.GetListOfKeys)
negative=f2.Get(i.Next.GetName).as("TH1F")
total.Add(total,negative,1,-1)
total.Divide(negative)
total.Scale(100)
f2.Close
output=TFile.new(opts_hash["--output-file"],"new")
total.Write

output.Write
output.Close
