/*
 * This file is generated by the Syntaxhighlighter module
 */
function syntaxhighlighterAutoloaderSetup() {
  SyntaxHighlighter.autoloader(
    'as3 /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushAS3.js',
    'applescript /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushAppleScript.js',
    'bash /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushBash.js',
    'csharp /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushCSharp.js',
    'coldfusion /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushColdFusion.js',
    'cpp /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushCpp.js',
    'css /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushCss.js',
    'delphi /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushDelphi.js',
    'diff /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushDiff.js',
    'erlang /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushErlang.js',
    'groovy /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushGroovy.js',
    'jscript /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushJScript.js',
    'java /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushJava.js',
    'javafx /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushJavaFX.js',
    'perl /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushPerl.js',
    'php /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushPhp.js',
    'plain /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushPlain.js',
    'powershell /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushPowerShell.js',
    'python /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushPython.js',
    'ruby /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushRuby.js',
    'sass /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushSass.js',
    'scala /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushScala.js',
    'sql /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushSql.js',
    'vb /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushVb.js',
    'xml /sites/all/libraries/syntaxhighlighter_3.0.83/scripts/shBrushXml.js'
);
}
