global stopvar
stopvar=0;
hfig=figure;
hbutGo=uicontrol(hfig,'Style','pushbutton',...
    'String','go','Callback','go',...
    'position',[20 20 40 40]);
hbutStop=uicontrol(hfig,'Style','pushbutton',...
    'String','stop','Callback','stop',...
    'position',[90 20 40 40]);
hbutStop=uicontrol(hfig,'Style','text',...
    'position',[90 90 40 40]);
