!
!  ConsoleApp.f90
!
!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  13.05.2014 11:29:53
!

      program prog

      implicit none

      ! Variables

      ! Body

      end program prog
