(function(l){l(window,"undefined"===typeof window._acic?{}:window._acic,"undefined"===typeof window._aci_debug?!1:window._aci_debug)})(function(l,k,s){function e(){if(!(this instanceof e))return new e;this.version="0.0.17";this.urlHit="//www.acint.net/hit/";this.urlJump="//www.acint.net/jump/";this.urlPing="//www.acint.net/ping/";this.urlMatchCookie="//www.acint.net/mc/";this.cookieName="aid";this.cookieValueOptOut="opt-out";this.uid="";this.presence={startTimeout:1E4,maxNofRequests:2,timeoutMultiplier:2,
nofRequests:0};this.config={dataProvider:"",allowExtLinksTrack:!0,allowPresenceTrack:!0,customData:null}}var t=!!s,q={};"object"==typeof JSON&&"function"==typeof JSON.stringify?q.stringify=function(a){return JSON.stringify(a)}:function(){function a(a){function b(a){return 10>a?"0"+a:a}if(a&&"object"==typeof a){if(a instanceof Date)return isFinite(a.valueOf())?a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+
"Z":null;if(a instanceof String||a instanceof Number||a instanceof Boolean)return a.valueOf()}return a}function c(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var b=r[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(g,r){var n,e,k,l,q=d,p,m=r[g],m=a(m);"function"===typeof h&&(m=h.call(r,g,m));switch(typeof m){case "string":return c(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);
case "object":if(!m)return"null";d+=f;p=[];if("[object Array]"===Object.prototype.toString.apply(m)){l=m.length;for(n=0;n<l;n+=1)p[n]=b(n,m)||"null";k=0===p.length?"[]":d?"[\n"+d+p.join(",\n"+d)+"\n"+q+"]":"["+p.join(",")+"]";d=q;return k}if(h&&"object"===typeof h)for(l=h.length,n=0;n<l;n+=1)e=h[n],"string"===typeof e&&(k=b(e,m))&&p.push(c(e)+(d?": ":":")+k);else for(e in m)Object.prototype.hasOwnProperty.call(m,e)&&(k=b(e,m))&&p.push(c(e)+(d?": ":":")+k);k=0===p.length?"{}":d?"{\n"+d+p.join(",\n"+
d)+"\n"+q+"}":"{"+p.join(",")+"}";d=q;return k}}var g,d,f,r,h;"function"!==typeof q.stringify&&(g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,r={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},q.stringify=function(a,c,g){var e;f=d="";if("number"===typeof g)for(e=0;e<g;e+=1)f+=" ";else"string"===typeof g&&(f=g);if((h=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSONStub.stringify");
return b("",{"":a})})}();var f={generateUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)}).toLowerCase()},stringTrimLimit:function(a){if(null==a)return"";a=a.replace(/\s+/gmi," ").replace(/^\s+|\s+$/g,"");1E3<a.length&&(a=a.substr(0,1E3));return a},padInt:function(a){return 10>a?"0"+a:""+a},getTimeZoneOffsetIso8601:function(){var a=(new Date).getTimezoneOffset();return(0<a?"-":"+")+this.padInt(Math.floor(Math.abs(a)/
60))+":"+this.padInt(Math.abs(a)%60)},getDateTimeIso8601:function(a){var c=new Date;return c.getFullYear()+"-"+this.padInt(c.getMonth()+1)+"-"+this.padInt(c.getDate())+"T"+this.padInt(c.getHours())+":"+this.padInt(c.getMinutes())+":"+this.padInt(c.getSeconds())+"."+String((c.getMilliseconds()/1E3).toFixed(3)).slice(2,5)+(!0===a?this.getTimeZoneOffsetIso8601:"")},isObject:function(a){return"object"===typeof a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"undefined"!==
typeof Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},isEmptyObject:function(a){for(var c in a)return!1;return!0},isString:function(a){return"string"===typeof a||a instanceof String},encodeUriParam:function(a){if(null==a)return"";a=""+a;return encodeURIComponent instanceof Function?encodeURIComponent(a):escape(a)},implodeUriParams:function(a){var c,b=[];for(c in a)a.hasOwnProperty(c)&&b.push(c+"="+a[c]);return b.join("&")},makeRequestUri:function(a,c){var b=f.implodeUriParams(c);
8E3<b.length&&(b=b.substr(0,8E3));return a+"?"+b},makeRequestImage:function(a){(window.Image?new Image:document.createElement("img")).src=a},makeRequestIframe:function(a){var c=document.createElement("iframe");c&&(c.setAttribute("src",a),c.setAttribute("style","width:1px;height:1px;display:none;"),document.body.appendChild(c))},addReadOnlyProperty:function(a,c,b){Object.defineProperty(a,c,{value:b,writeable:!1,enumerable:!0,configurable:!1})},addEventListenerCrossBrowser:function(a,c,b){if(a.addEventListener)a.addEventListener(c,
b,!1);else if(a.attachEvent)a.attachEvent("on"+c,b);else throw"Cannot add event listener: no Event API support in client";},removeEventListenerCrossBrowser:function(a,c,b){if(a.removeEventListener)a.removeEventListener(c,b,!1);else if(a.attachEvent)a.detachEvent("on"+c,b);else throw"Cannot remove event listener: no Event API support in client";},fireEventCrossBrowser:function(a,c){var b,g=document;if(g.createEvent){var d=null;switch(c){case "click":case "dblclick":case "mousedown":case "mouseup":case "mouseover":case "mousemove":case "mouseout":case "mouseenter":case "mouseleave":d=
"MouseEvent";break;case "wheel":d="WheelEvent";break;case "load":case "unload":case "abort":case "error":case "select":case "resize":case "scroll":d="UIEvent";break;case "focus":case "focusin":case "focusout":case "blur":d="FocusEvent";break;case "beforeinput":case "input":d="InputEvent";break;case "keydown":case "keyup":d="KeyboardEvent";break;case "compositionstart":case "compositionupdate":case "compositionend":d="CompositionEvent"}try{b=g.createEvent(d)}catch(f){try{b=g.createEvent("HtmlEvents")}catch(e){try{b=
g.createEvent("Event")}catch(h){throw Error("Cannot create event object for specified event: "+c);}}}b.initEvent(c,!0,!1);a.dispatchEvent(b)}else if(g.createEventObject)b=g.createEventObject(),b.eventType=c,a.fireEvent("on"+c,b);else if("function"==typeof a["on"+c])a["on"+c]()},fireSameEventCrosBrowser:function(a,c,b){var g=document,d;if(g.createEvent)try{d=new b.constructor(c,b),a.dispatchEvent(d)}catch(f){d=g.createEvent("MouseEvent"),d.initMouseEvent(b.type,!0,!0,window,0,b.screenX,b.screenY,b.clientX,
b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget||null),a.dispatchEvent(d)}else if(g.createEventObject)d=g.createEventObject(b),d.eventType=c,a.fireEvent("on"+c,d);else if("function"==typeof a["on"+c])a["on"+c]()},bindOnReady:function(a){function c(){g||(g=!0,a())}function b(){if(!g)try{e.doScroll("left"),c()}catch(a){setTimeout(b,10)}}var g=!1,d=window,f=document,e=f.documentElement;if(f.addEventListener)f.addEventListener("DOMContentLoaded",c,!1);else if(f.attachEvent){try{var h=
null!=d.frameElement}catch(k){}e.doScroll&&!h&&b();f.attachEvent("onreadystatechange",function(){"complete"===f.readyState&&c()})}else if(d.addEventListener)d.addEventListener("load",c,!1);else if(d.attachEvent)d.attachEvent("onload",c);else{var l=d.onload;d.onload=function(){l&&l();c()}}},cookies:{getItem:function(a){return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null},setItem:function(a,
c,b,g,d,f){if(!a||/^(?:expires|max\-age|path|domain|secure)$/i.test(a))return!1;var e="";if(b)switch(b.constructor){case Number:e=Infinity===b?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+b;break;case String:e="; expires="+b;break;case Date:e="; expires="+b.toUTCString()}document.cookie=encodeURIComponent(a)+"="+encodeURIComponent(c)+e+(d?"; domain="+d:"")+(g?"; path="+g:"")+(f?"; secure":"");return!0},removeItem:function(a,c,b){if(!a||!this.hasItem(a))return!1;document.cookie=encodeURIComponent(a)+
"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(b?"; domain="+b:"")+(c?"; path="+c:"");return!0},hasItem:function(a){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)},keys:function(){for(var a=document.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/),c=0;c<a.length;c++)a[c]=decodeURIComponent(a[c]);return a}}};e.prototype.init=function(){this.isAlreadyLoaded()||f.cookies.hasItem(this.cookieName)&&
this.cookieValueOptOut==f.cookies.getItem(this.cookieName)||(this.uid=f.generateUUID(),this.parseConfig(),this.initHit(),this.initCookieMatch(),!0===this.config.allowExtLinksTrack&&this.initExtLinksTrack(),!0===this.config.allowPresenceTrack&&this.initPresenceTrack())};e.prototype.initHit=function(){var a=f.makeRequestUri(this.urlHit,this.collectDataOnInit());f.makeRequestImage(a)};e.prototype.initCookieMatch=function(){if(150==this.config.dataProvider){var a=f.makeRequestUri(this.urlMatchCookie,
this.collectDataOnCookieMatch());f.makeRequestIframe(a)}};e.prototype.initExtLinksTrack=function(){var a=this,c=document,b=function(b){var c=window,e=!1,k;b=b||c.event;var h=b.target||b.srcElement,l=h;if(!("tagName"in h&&"a"==h.tagName.toLowerCase())){for(e=h.parentNode;e;){if("tagName"in e&&"a"==e.tagName.toLowerCase()){k=e;break}if("parentNode"in e)e=e.parentNode;else break}if(k)h=k;else return}if("href"in h&&/^(http:|https:|)\/\/.+/.test(h.href)&&!("hostname"in h&&h.hostname===c.location.hostname)){if(b.shiftKey||
b.altKey||b.ctrlKey||b.metaKey)e=!0;e=!0;h.hasOwnProperty("_delayClick")?!1===h.hasOwnProperty("_canSkipDelay")?"preventDefault"in b?b.preventDefault():b.returnValue=!1:(delete h._canSkipDelay,delete h._delayClick):(c=f.makeRequestUri(a.urlJump,a.collectDataOnClick(b,h)),f.makeRequestImage(c),!1===e&&(h._delayClick=!0,setTimeout(function(){h._canSkipDelay=!0;f.fireSameEventCrosBrowser(l,"click",b)},200),"preventDefault"in b?b.preventDefault():b.returnValue=!1))}};"interactive"==c.readyState||"complete"==
c.readyState?f.addEventListenerCrossBrowser(c.body,"click",b):f.bindOnReady(function(){f.addEventListenerCrossBrowser(c.body,"click",b)})};e.prototype.initPresenceTrack=function(){var a=this,c=function(){var b=f.makeRequestUri(a.urlPing,a.collectDataOnPresencePing());f.makeRequestImage(b);a.presence.nofRequests+=1;a.presence.nofRequests<a.presence.maxNofRequests&&(b=a.presence.startTimeout*Math.pow(a.presence.timeoutMultiplier,a.presence.nofRequests),setTimeout(c,b))};setTimeout(c,this.presence.startTimeout)};
e.prototype.isAlreadyLoaded=function(){if("object"==typeof l._acil&&"function"==typeof l._acil.isLoaded)return!0;"undefined"!==typeof Object.defineProperty?(f.addReadOnlyProperty(l,"_acil",{}),f.addReadOnlyProperty(l._acil,"isLoaded",function(){return!0})):l._acil=function(){return{isLoaded:function(){return!0}}}();return!1};e.prototype.parseConfig=function(){if(f.isObject(k)&&!f.isEmptyObject(k)){var a=["dataProvider"],c=["allowExtLinksTrack","allowPresenceTrack"],b=["customData"],g,d;for(d=0;d<
a.length;d++)g=a[d],k.hasOwnProperty(g)&&(this.config[g]=isNaN(parseInt(k[g],10))?this.config[g]:Math.abs(parseInt(k[g],10)));for(d=0;d<c.length;d++)g=c[d],k.hasOwnProperty(g)&&(this.config[g]=!0===k[g]);for(d=0;d<b.length;d++)if(g=b[d],k.hasOwnProperty(g)&&(a=k[g],!("undefined"===typeof a||null==a||"function"==typeof a||f.isString(a)&&0===a.length||f.isObject(a)&&f.isEmptyObject(a)||f.isArray(a)&&0===a.length))){try{if(f.isObject(a)||f.isArray(a)){if(a=q.stringify(a),"{}"===a||"[]"===a)a=null}else f.isString(a)||
(a=a.toString(),0===a.length&&(a=null))}catch(e){if(a=null,!0===s)throw e;}this.config[g]=a}}};e.prototype.dataAddObligatoryParams=function(a){a.v=this.version;a.uid=this.uid;a.dp=this.config.dataProvider;a.tz=f.encodeUriParam(f.getTimeZoneOffsetIso8601());a.nc=Math.random().toString().substr(2,8);return a};e.prototype.collectDataOnInit=function(){var a=document,c=window,b=this.dataAddObligatoryParams({});b.u=f.encodeUriParam(f.stringTrimLimit(c.location.href));b.r=f.encodeUriParam(f.stringTrimLimit(a.referrer||
""));b.rs=c.screen.width+"x"+c.screen.height;b.t=f.encodeUriParam(f.stringTrimLimit(a.title));b.oE=+this.config.allowExtLinksTrack;b.oP=+this.config.allowPresenceTrack;b.dT=f.encodeUriParam(f.getDateTimeIso8601(!1));null!==this.config.customData&&(b.cd=f.encodeUriParam(f.stringTrimLimit(this.config.customData)));c.parent!==c&&(b["if"]=f.encodeUriParam(c.location.href),b.u=f.encodeUriParam(a.referrer||""),b.r="");return b};e.prototype.collectDataOnCookieMatch=function(){return{dp:this.config.dataProvider}};
e.prototype.collectDataOnClick=function(a,c){var b=document,g=window,b=a.target.ownerDocument||b,d=b.documentElement,e=b.body,b=this.dataAddObligatoryParams({});b.u="";b.r="";b.vP="";b.c="";b.aT="";b.hT=0;b.vP=(g.innerWidth||d.clientWidth||e.clientWidth)+"x"+(g.innerHeight||d.clientHeight||e.clientHeight);null==a.pageX&&null!=a.clientX?b.c=a.clientX+(d&&d.scrollLeft||e&&e.scrollLeft||0)-(d&&d.clientLeft||e&&e.clientLeft||0)+"x"+(a.clientY+(d&&d.scrollTop||e&&e.scrollTop||0)-(d&&d.clientTop||e&&e.clientTop||
0)):null!==a.pageX&&(b.c=a.pageX+"x"+a.pageY);b.r=f.encodeUriParam(f.stringTrimLimit(g.location.href));b.u=f.encodeUriParam(f.stringTrimLimit(c.href));var g=c.childNodes,k=0,h=0,l=0;if(1<=g.length){for(d=0;d<g.length;d++)e=g[d],3!==e.nodeType&&1!==e.nodeType||1!==e.nodeType||(h+=1,"tagName"in g[d]&&"img"===g[d].tagName.toLowerCase()&&(k+=1,l=d));1==k&&k==h?b.hT=1:0<h&&(b.hT=2)}switch(b.hT){case 1:b.aT=g[l].getAttribute("alt")||"";break;case 2:case 0:b.aT=c.innerHTML?c.innerHTML.toString().replace(/<\/?[^>]+>/gmi,
""):""}0<b.aT.length&&(b.aT=f.stringTrimLimit(b.aT),""!==b.aT&&(b.aT=/^(\S+(\s|)){1,10}/gmi.exec(b.aT)[0].replace(/^\s+|\s+$/g,"")));b.aT=f.encodeUriParam(b.aT);return b};e.prototype.collectDataOnPresencePing=function(){var a=this.dataAddObligatoryParams({});a.dT=f.encodeUriParam(f.getDateTimeIso8601(!1));return a};try{(new e).init()}catch(u){if(!0===t)throw u;}});
